/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin library project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.2.1/userguide/building_java_projects.html in the Gradle documentation.
 */
import com.vanniktech.maven.publish.JavadocJar
import com.vanniktech.maven.publish.SourcesJar

plugins {
    // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
    alias(libs.plugins.kotlin.jvm)

    // Apply the java-library plugin for API and implementation separation.
    `java-library`
    id("com.vanniktech.maven.publish") version "0.36.0"
    signing
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use the Kotlin Test integration.
    testImplementation("org.jetbrains.kotlin:kotlin-test")

    // Use the JUnit 5 integration.
    testImplementation(libs.junit.jupiter.engine)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // This dependency is exported to consumers, that is to say found on their compile classpath.
    api(libs.commons.math3)

    // This dependency is used internally, and not exposed to consumers on their own compile classpath.
    implementation(libs.guava)
    
    compileOnly(files(
        "libs/android.jar",
        "libs/documentfile-1.1.0.jar"
    ))
}

val groupId = "io.github.sifisofakude"
val artifactId = "filesystem"
val version = "0.1.0"


mavenPublishing {
    configureBasedOnAppliedPlugins(
        javadocJar = JavadocJar.Javadoc(),
        sourcesJar = SourcesJar.Sources()
    )
    publishToMavenCentral()

    signAllPublications()

    coordinates(groupId.toString(),artifactId,version)

    pom    {
        name.set("FileSystem Utility")
        description.set("Minimal file/folder access for reading and writing on desktop/Android platform")
        url.set("https://github.com")

        licenses    {
            license     {
                name = "The MIT License"
                url = "https://opensource.org"
                distribution.set("repo")
            }
        }

        developers  {
            developer   {
                id = "sifisofakude"
                name = "Sifiso Fakude"
                email = "sifisofakude404@gmail.com"
            }
        }

        scm {
            connection = "scm:git:git://://github.com"
            developerConnection = "scm:git:ssh://github.com:sifisofakude/filesystem.git"
            url = "https://github.com"
        }
    }
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}
