[versions]
kotlinxIo = "0.9.1"
documentfile = "1.1.0"
startup = "1.2.0"
kotlin = "2.4.10"
agp = "9.2.0"

[libraries]
kotlinx-io-core = {module = "org.jetbrains.kotlinx:kotlinx-io-core", versionRef = "kotlinxIo"}

androidx-documentfile = {module = "androidx.documentfile:documentfile",versionRef = "documentfile"}

androidx-statup = {module = "androidx.statup:statup-runtime",versionRef = "statup"}

[plugins]
kotlin-multiplatform = {id = "org.jetbrains.kotlin.multiplatform",versionRef = "kotlin"}

android-kmp = {id = "com.android.kotlin.multiplatform",versionRef = "agp"}

maven-publish = {id = "maven-publish"}
