[versions]
kotlinxIo = "0.9.1"
documentfile = "1.1.0"
startup = "1.2.0"
kotlin = "2.4.10"
agp = "9.2.0"

[libraries]
kotlinx-io-core = {module = "org.jetbrains.kotlinx:kotlinx-io-core", version.ref = "kotlinxIo"}

androidx-documentfile = {module = "androidx.documentfile:documentfile",version.ref = "documentfile"}

androidx-startup = {module = "androidx.startup:startup-runtime",version.ref = "startup"}

[plugins]
kotlin-multiplatform = {id = "org.jetbrains.kotlin.multiplatform",version.ref = "kotlin"}

android-kmp = {id = "com.android.kotlin.multiplatform",version.ref = "agp"}

maven-publish = {id = "maven-publish"}
